spring:
  server:
    port: 8080
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/xubb_test1
    username: root
    password: bobo1356
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
